version: '3'
services:
  web:
    image: node:latest
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: direx
      POSTGRES_PASSWORD: direx
      POSTGRES_DB: db_direx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  